(function() {
  return [
    ['LEFT'   , bhTextDb.get('node', 'key-pressed-events', 'LEFT')],
    ['RIGHT'  , bhTextDb.get('node', 'key-pressed-events', 'RIGHT')],
    ['UP'     , bhTextDb.get('node', 'key-pressed-events', 'UP')],
    ['DOWN'   , bhTextDb.get('node', 'key-pressed-events', 'DOWN')],
    ['SPACE'  , bhTextDb.get('node', 'key-pressed-events', 'SPACE')],
    ['ENTER'  , bhTextDb.get('node', 'key-pressed-events', 'ENTER')],
    ['SHIFT'  , bhTextDb.get('node', 'key-pressed-events', 'SHIFT')],
    ['CTRL'   , bhTextDb.get('node', 'key-pressed-events', 'CTRL')],
    ['DIGIT0' , bhTextDb.get('node', 'key-pressed-events', 'DIGIT0')],
    ['DIGIT1' , bhTextDb.get('node', 'key-pressed-events', 'DIGIT1')],
    ['DIGIT2' , bhTextDb.get('node', 'key-pressed-events', 'DIGIT2')],
    ['DIGIT3' , bhTextDb.get('node', 'key-pressed-events', 'DIGIT3')],
    ['DIGIT4' , bhTextDb.get('node', 'key-pressed-events', 'DIGIT4')],
    ['DIGIT5' , bhTextDb.get('node', 'key-pressed-events', 'DIGIT5')],
    ['DIGIT6' , bhTextDb.get('node', 'key-pressed-events', 'DIGIT6')],
    ['DIGIT7' , bhTextDb.get('node', 'key-pressed-events', 'DIGIT7')],
    ['DIGIT8' , bhTextDb.get('node', 'key-pressed-events', 'DIGIT8')],
    ['DIGIT9' , bhTextDb.get('node', 'key-pressed-events', 'DIGIT9')],
    ['A'      , bhTextDb.get('node', 'key-pressed-events', 'A')],
    ['B'      , bhTextDb.get('node', 'key-pressed-events', 'B')],
    ['C'      , bhTextDb.get('node', 'key-pressed-events', 'C')],
    ['D'      , bhTextDb.get('node', 'key-pressed-events', 'D')],
    ['E'      , bhTextDb.get('node', 'key-pressed-events', 'E')],
    ['F'      , bhTextDb.get('node', 'key-pressed-events', 'F')],
    ['G'      , bhTextDb.get('node', 'key-pressed-events', 'G')],
    ['H'      , bhTextDb.get('node', 'key-pressed-events', 'H')],
    ['I'      , bhTextDb.get('node', 'key-pressed-events', 'I')],
    ['J'      , bhTextDb.get('node', 'key-pressed-events', 'J')],
    ['K'      , bhTextDb.get('node', 'key-pressed-events', 'K')],
    ['L'      , bhTextDb.get('node', 'key-pressed-events', 'L')],
    ['M'      , bhTextDb.get('node', 'key-pressed-events', 'M')],
    ['N'      , bhTextDb.get('node', 'key-pressed-events', 'N')],
    ['O'      , bhTextDb.get('node', 'key-pressed-events', 'O')],
    ['P'      , bhTextDb.get('node', 'key-pressed-events', 'P')],
    ['Q'      , bhTextDb.get('node', 'key-pressed-events', 'Q')],
    ['R'      , bhTextDb.get('node', 'key-pressed-events', 'R')],
    ['S'      , bhTextDb.get('node', 'key-pressed-events', 'S')],
    ['T'      , bhTextDb.get('node', 'key-pressed-events', 'T')],
    ['U'      , bhTextDb.get('node', 'key-pressed-events', 'U')],
    ['V'      , bhTextDb.get('node', 'key-pressed-events', 'V')],
    ['W'      , bhTextDb.get('node', 'key-pressed-events', 'W')],
    ['X'      , bhTextDb.get('node', 'key-pressed-events', 'X')],
    ['Y'      , bhTextDb.get('node', 'key-pressed-events', 'Y')],
    ['Z'      , bhTextDb.get('node', 'key-pressed-events', 'Z')]
  ];
})();
